/**
 * Manages the lifecycle of the plugin's injected CSS style element.
 *
 * A single <style> tag is created in the document <head> on construction
 * and reused for all subsequent style updates, avoiding duplicate elements.
 *
 * Note: This plugin intentionally creates a <style> element at runtime because
 * the CSS it generates is fully dynamic — it depends on user-defined colors that
 * are only known at runtime and change per vault. A static styles.css file cannot
 * cover this use case.
 */
export class StyleManager {
	private styleEl: HTMLStyleElement;

	/**
	 * Creates the style element and appends it to the document head.
	 * Should be instantiated once per plugin lifecycle.
	 */
	constructor() {
		// eslint-disable-next-line obsidianmd/no-forbidden-elements
		this.styleEl = document.createElement('style');
		this.styleEl.id = 'folder-color-plugin-styles';
		document.head.appendChild(this.styleEl);
	}

	/**
	 * Replaces the current CSS content with the provided string.
	 * Called every time folder/file colors change.
	 *
	 * @param css - Full CSS string generated by ColorManager.
	 */
	applyStyles(css: string) {
		this.styleEl.textContent = css;
	}

	/**
	 * Removes the style element from the DOM.
	 * Called on plugin unload to avoid leaving orphan styles behind.
	 */
	removeStyles() {
		this.styleEl.remove();
	}
}
